package wtc

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
)

// AgentToolchainPath collects sibling mise bins, keeping product repositories
// ahead of the harness and collection pins. A valid cache is used when possible.
func (c *Context) AgentToolchainPath(force bool) (string, error) {
	cache := filepath.Join(c.Collection, ".env.toolchain")
	if !force && toolchainCacheFresh(c.Collection, cache) {
		return readToolchainCache(cache), nil
	}
	previous := readToolchainCache(cache)
	path, err := c.computeAgentToolchainPath()
	if err != nil {
		return "", err
	}
	if path == "" && previous != "" && !agentEnvConfigNewer(c.Collection, cache) {
		return previous, nil // A bare agent shell must not erase a useful cache.
	}
	data := []byte("# Generated by wtc agent-env — machine-local toolchain bins.\n" +
		"# Prepend WTC_TOOLCHAIN_PATH to PATH for agent shells.\n" +
		"WTC_TOOLCHAIN_PATH=" + path + "\n")
	tmp, err := os.CreateTemp(c.Collection, ".env.toolchain-*")
	if err != nil {
		return "", err
	}
	defer os.Remove(tmp.Name())
	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		return "", err
	}
	if err := tmp.Close(); err != nil {
		return "", err
	}
	if err := os.Rename(tmp.Name(), cache); err != nil {
		return "", err
	}
	return path, nil
}

func agentEnvConfigNewer(collection, cache string) bool {
	configInfo, configErr := os.Stat(filepath.Join(collection, "harness", "wtc.toml"))
	cacheInfo, cacheErr := os.Stat(cache)
	return configErr == nil && cacheErr == nil && configInfo.ModTime().After(cacheInfo.ModTime())
}

func readToolchainCache(path string) string {
	data, err := os.ReadFile(path)
	if err != nil {
		return ""
	}
	for _, line := range strings.Split(string(data), "\n") {
		if strings.HasPrefix(line, "WTC_TOOLCHAIN_PATH=") {
			return strings.TrimPrefix(line, "WTC_TOOLCHAIN_PATH=")
		}
	}
	return ""
}

func toolchainCacheFresh(collection, cache string) bool {
	info, err := os.Stat(cache)
	if err != nil || readToolchainCache(cache) == "" {
		return false
	}
	for _, dir := range filepath.SplitList(readToolchainCache(cache)) {
		if dir != "" {
			if st, err := os.Stat(dir); err != nil || !st.IsDir() {
				return false
			}
		}
	}
	configs, _ := filepath.Glob(filepath.Join(collection, "*", "mise.toml"))
	configs = append(configs, filepath.Join(collection, "mise.toml"), filepath.Join(collection, "harness", "wtc.toml"))
	for _, config := range configs {
		if st, err := os.Stat(config); err == nil && st.ModTime().After(info.ModTime()) {
			return false
		}
	}
	return true
}

func (c *Context) computeAgentToolchainPath() (string, error) {
	seen := map[string]bool{}
	bins := []string{}
	for _, path := range c.Config.AgentEnv.PrependPaths {
		clean := filepath.Clean(path)
		if path == "" || filepath.IsAbs(path) || clean == "." || clean == ".." || strings.HasPrefix(clean, ".."+string(os.PathSeparator)) || strings.ContainsRune(path, os.PathListSeparator) {
			return "", fmt.Errorf("invalid agent_env.prepend_paths entry %q", path)
		}
		absolute := filepath.Join(c.Collection, clean)
		if st, err := os.Stat(absolute); err == nil && st.IsDir() && !seen[absolute] {
			seen[absolute] = true
			bins = append(bins, absolute)
		}
	}
	if _, err := exec.LookPath("mise"); err != nil {
		return strings.Join(bins, string(os.PathListSeparator)), nil
	}
	configs, _ := filepath.Glob(filepath.Join(c.Collection, "*", "mise.toml"))
	dirs := []string{}
	harness := ""
	for _, config := range configs {
		dir := filepath.Dir(config)
		if dir == c.Harness {
			harness = dir
		} else {
			dirs = append(dirs, dir)
		}
	}
	if harness != "" {
		dirs = append(dirs, harness)
	}
	dirs = append(dirs, c.Collection)
	for _, dir := range dirs {
		config := filepath.Join(dir, "mise.toml")
		if _, err := os.Stat(config); err != nil {
			continue
		}
		_ = exec.Command("mise", "trust", config).Run()
		out, err := exec.Command("mise", "-C", dir, "bin-paths").Output()
		if err != nil {
			continue
		}
		for _, line := range strings.Split(string(out), "\n") {
			line = strings.TrimSpace(line)
			if line == "" || seen[line] {
				continue
			}
			if st, err := os.Stat(line); err == nil && st.IsDir() {
				seen[line] = true
				bins = append(bins, line)
			}
		}
	}
	return strings.Join(bins, string(os.PathListSeparator)), nil
}

func AgentEnvEval(path string) string {
	if path == "" {
		return ""
	}
	quoted := "'" + strings.ReplaceAll(path, "'", "'\\''") + "'"
	return "# wtc-agent-env\n" +
		"WTC_AGENT_ENV=1\nWTC_TOOLCHAIN_PATH=" + quoted + "\n" +
		"case \":${PATH:-}:\" in *\":${WTC_TOOLCHAIN_PATH}:\"*) ;; *)\n" +
		"  PATH=\"${WTC_TOOLCHAIN_PATH}${PATH:+:$PATH}\" ;;\n" +
		"esac\nexport WTC_AGENT_ENV WTC_TOOLCHAIN_PATH PATH\n"
}

var safeAgentEnvPath = regexp.MustCompile(`^[A-Za-z0-9_@%+=:,./-]+$`)

// AgentEnvWrap rewrites a PreToolUse command. Invalid or unsupported input is
// deliberately ignored so tool hooks fail open.
func AgentEnvWrap(raw []byte, script string) []byte {
	if !safeAgentEnvPath.MatchString(script) {
		return nil
	}
	var event map[string]json.RawMessage
	if json.Unmarshal(raw, &event) != nil {
		return nil
	}
	field := event["toolInput"]
	if len(field) == 0 {
		field = event["tool_input"]
	}
	var input map[string]json.RawMessage
	if json.Unmarshal(field, &input) != nil {
		return nil
	}
	var command string
	if json.Unmarshal(input["command"], &command) != nil || strings.TrimSpace(command) == "" {
		return nil
	}
	if strings.HasPrefix(strings.TrimLeft(command, " \t\n"), "# wtc-agent-env") || strings.Contains(firstN(command, 400), "WTC_AGENT_ENV=1") {
		return nil
	}
	wrapped := "# wtc-agent-env\neval \"$(bash " + script + ")\"\n" + command
	value, _ := json.Marshal(wrapped)
	input["command"] = value
	output := map[string]any{"hookSpecificOutput": map[string]any{"hookEventName": "PreToolUse", "updatedInput": input}}
	data, err := json.Marshal(output)
	if err != nil {
		return nil
	}
	return bytes.TrimSpace(data)
}

func firstN(s string, n int) string {
	if len(s) > n {
		return s[:n]
	}
	return s
}

func AgentEnvScriptPath(collection string) (string, error) {
	script := filepath.Join(collection, "harness", "tools", "agent-env.sh")
	if !safeAgentEnvPath.MatchString(script) {
		return "", fmt.Errorf("agent-env wrapper requires a shell-safe collection path")
	}
	return script, nil
}
