package wtc

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
)

var safeName = regexp.MustCompile(`[^a-z0-9_-]`)

func agentName(session, collection string) string {
	s := safeName.ReplaceAllString(strings.ToLower(session), "-")
	c := safeName.ReplaceAllString(strings.ToLower(collection), "-")
	if s == "" || s[0] < 'a' || s[0] > 'z' {
		s = "w" + s
	}
	room := 32 - len(s) - 2
	if room < 1 {
		if len(s) > 32 {
			return s[:32]
		}
		return s
	}
	if len(c) > room {
		c = c[:room]
	}
	return s + "--" + c
}
func (c *Context) session() string {
	if c.Config.Herdr.Session != "" {
		return c.Config.Herdr.Session
	}
	name := filepath.Base(c.Workspace)
	name = strings.TrimSuffix(name, "-harness")
	return strings.TrimSuffix(name, "-wtc")
}
func (c *Context) portBase() (int, error) {
	old, _ := os.ReadFile(filepath.Join(c.Collection, ".env.collection"))
	for _, line := range strings.Split(string(old), "\n") {
		if strings.HasPrefix(line, "COLLECTION_PORT_BASE=") {
			return strconv.Atoi(strings.TrimPrefix(line, "COLLECTION_PORT_BASE="))
		}
	}
	used := map[int]bool{}
	dirs, err := os.ReadDir(c.Workspace)
	if err != nil {
		return 0, err
	}
	for _, d := range dirs {
		if !d.IsDir() {
			continue
		}
		b, _ := os.ReadFile(filepath.Join(c.Workspace, d.Name(), ".env.collection"))
		for _, line := range strings.Split(string(b), "\n") {
			if strings.HasPrefix(line, "COLLECTION_PORT_BASE=") {
				n, _ := strconv.Atoi(strings.TrimPrefix(line, "COLLECTION_PORT_BASE="))
				used[n] = true
			}
		}
	}
	for n := 42000; n < 65000; n += 100 {
		if !used[n] {
			return n, nil
		}
	}
	return 0, fmt.Errorf("no free collection port block")
}
func (c *Context) RenderEnv() ([]byte, error) {
	base, err := c.portBase()
	if err != nil {
		return nil, err
	}
	name := filepath.Base(c.Collection)
	var b bytes.Buffer
	fmt.Fprintln(&b, "# Generated by wtc — collection-scoped env (not committed).")
	fmt.Fprintln(&b, "# Ports cover every registry repo with a port_offset, whether or not")
	fmt.Fprintln(&b, "# it is checked out here, so absent repos still resolve to a port.")
	fmt.Fprintf(&b, "WTC_COLLECTION=%s\nWTC_AGENT_NAME=%s\nWTC_CONFIG_ROOT=%s\nCOLLECTION_PORT_BASE=%d\n", name, agentName(c.session(), name), c.ConfigRoot, base)
	for _, r := range c.Registry.Repos {
		if r.PortOffset == nil {
			continue
		}
		key := strings.ToUpper(strings.ReplaceAll(r.Name, "-", "_")) + "_PORT"
		fmt.Fprintf(&b, "%s=%d\n", key, base+*r.PortOffset)
	}
	gh := filepath.Join(c.ConfigRoot, "gh")
	jira := filepath.Join(c.ConfigRoot, "jira")
	_, ghErr := os.Stat(gh)
	_, jiraErr := os.Stat(jira)
	twg := os.Getenv("WTC_TWG_SITE")
	if ghErr == nil || jiraErr == nil || twg != "" {
		fmt.Fprintln(&b, "\n# Tool identity — workspace CLI stores, never credentials.")
		if ghErr == nil {
			fmt.Fprintf(&b, "GH_CONFIG_DIR=%s\n", gh)
		}
		if jiraErr == nil {
			fmt.Fprintf(&b, "JIRA_CONFIG_FILE=%s\n", filepath.Join(jira, ".config.yml"))
		}
		if twg != "" {
			fmt.Fprintf(&b, "TWG_SITE=%s\n", twg)
		}
	}
	return b.Bytes(), nil
}
func (c *Context) WriteEnv(data []byte) error {
	target := filepath.Join(c.Collection, ".env.collection")
	tmp, err := os.CreateTemp(c.Collection, ".env.collection.tmp-")
	if err != nil {
		return err
	}
	defer os.Remove(tmp.Name())
	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Chmod(0644); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	return os.Rename(tmp.Name(), target)
}

const miseFile = `# Generated by wtc. Collection-scoped env inherited by sibling worktrees.
[env]
_.file = [".env.collection", ".env.collection.local"]
`
const localEnvFile = `# Collection-scoped secrets and overrides. Hand-authored; never regenerated.
`

func (c *Context) EnsureEnvSupport() error {
	local := filepath.Join(c.Collection, ".env.collection.local")
	if err := c.ValidateEnvSupport(); err != nil {
		return err
	}
	if _, err := os.Lstat(local); os.IsNotExist(err) {
		f, err := os.OpenFile(local, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0600)
		if err != nil {
			return err
		}
		if _, err := f.WriteString(localEnvFile); err != nil {
			f.Close()
			return err
		}
		if err := f.Close(); err != nil {
			return err
		}
	} else {
		return err
	}
	if err := os.Chmod(local, 0600); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(c.Collection, "mise.toml"), []byte(miseFile), 0644)
}

func (c *Context) ValidateEnvSupport() error {
	local := filepath.Join(c.Collection, ".env.collection.local")
	info, err := os.Lstat(local)
	if err == nil && info.Mode()&os.ModeSymlink != 0 {
		return fmt.Errorf("refusing symlink: %s", local)
	}
	if err != nil && !os.IsNotExist(err) {
		return err
	}
	return nil
}
