package wtc

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

var safeName = regexp.MustCompile(`[^a-z0-9_-]`)

func agentName(session, collection string) string {
	s := safeName.ReplaceAllString(strings.ToLower(session), "-")
	c := safeName.ReplaceAllString(strings.ToLower(collection), "-")
	if s == "" || s[0] < 'a' || s[0] > 'z' {
		s = "w" + s
	}
	room := 32 - len(s) - 2
	if room < 1 {
		if len(s) > 32 {
			return s[:32]
		}
		return s
	}
	if len(c) > room {
		c = c[:room]
	}
	return s + "--" + c
}
func (c *Context) session() string {
	if c.Config.Herdr.Session != "" {
		return c.Config.Herdr.Session
	}
	name := filepath.Base(c.Workspace)
	name = strings.TrimSuffix(name, "-harness")
	return strings.TrimSuffix(name, "-wtc")
}
func (c *Context) portBase() (int, error) {
	if c.previewPortBase != nil {
		return *c.previewPortBase, nil
	}
	return c.portBaseWithReserved(nil)
}

// PreviewPortBase reserves an allocation in memory for a dry-run sweep.
// The caller adds a successful result to reserved before previewing the next
// collection; no collection file is written during the preview.
func (c *Context) PreviewPortBase(reserved map[int]bool) (int, error) {
	base, err := c.portBaseWithReserved(reserved)
	if err == nil {
		c.previewPortBase = &base
	}
	return base, err
}

func (c *Context) portBaseWithReserved(reserved map[int]bool) (int, error) {
	old, err := os.ReadFile(filepath.Join(c.Collection, ".env.collection"))
	if err != nil && !os.IsNotExist(err) {
		return 0, err
	}
	for _, line := range strings.Split(string(old), "\n") {
		if strings.HasPrefix(line, "COLLECTION_PORT_BASE=") {
			return parsePortBase(line)
		}
	}
	used := map[int]bool{}
	for base := range reserved {
		used[base] = true
	}
	dirs, err := os.ReadDir(c.Workspace)
	if err != nil {
		return 0, err
	}
	for _, d := range dirs {
		if !d.IsDir() {
			continue
		}
		b, err := os.ReadFile(filepath.Join(c.Workspace, d.Name(), ".env.collection"))
		if os.IsNotExist(err) {
			continue
		}
		if err != nil {
			return 0, err
		}
		for _, line := range strings.Split(string(b), "\n") {
			if strings.HasPrefix(line, "COLLECTION_PORT_BASE=") {
				n, err := parsePortBase(line)
				if err != nil {
					return 0, fmt.Errorf("%s: %w", d.Name(), err)
				}
				used[n] = true
			}
		}
	}
	for n := 42000; n < 65000; n += 100 {
		if !used[n] {
			return n, nil
		}
	}
	return 0, fmt.Errorf("no free collection port block")
}

func parsePortBase(line string) (int, error) {
	n, err := strconv.Atoi(strings.TrimPrefix(line, "COLLECTION_PORT_BASE="))
	if err != nil || n < 1 || n > 65535 {
		return 0, fmt.Errorf("invalid collection port base %q", line)
	}
	return n, nil
}

func portKey(name string) string {
	return strings.ToUpper(strings.ReplaceAll(name, "-", "_")) + "_PORT"
}

func quotedValue(value string) (string, error) {
	if strings.ContainsAny(value, "'\r\n\x00") {
		return "", fmt.Errorf("environment value contains unsupported quote or newline")
	}
	return "'" + value + "'", nil
}

func machineTWGSite(root string) (string, error) {
	if value, exists := os.LookupEnv("WTC_TWG_SITE"); exists {
		return value, nil
	}
	data, err := os.ReadFile(filepath.Join(root, "wtc.env"))
	if os.IsNotExist(err) {
		return "", nil
	}
	if err != nil {
		return "", err
	}
	var value string
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		line = strings.TrimPrefix(line, "export ")
		if !strings.HasPrefix(line, "WTC_TWG_SITE=") {
			continue
		}
		value = strings.TrimSpace(strings.TrimPrefix(line, "WTC_TWG_SITE="))
		if len(value) >= 2 && (value[0] == '\'' && value[len(value)-1] == '\'' || value[0] == '"' && value[len(value)-1] == '"') {
			value = value[1 : len(value)-1]
		}
	}
	return value, nil
}
func (c *Context) RenderEnv() ([]byte, error) {
	base, err := c.portBase()
	if err != nil {
		return nil, err
	}
	name := filepath.Base(c.Collection)
	var b bytes.Buffer
	fmt.Fprintln(&b, "# Generated by wtc — collection-scoped env (not committed).")
	fmt.Fprintln(&b, "# Ports cover every registry repo with a port_offset, whether or not")
	fmt.Fprintln(&b, "# it is checked out here, so absent repos still resolve to a port.")
	for _, entry := range []struct{ key, value string }{{"WTC_COLLECTION", name}, {"WTC_AGENT_NAME", agentName(c.session(), name)}, {"WTC_CONFIG_ROOT", c.ConfigRoot}} {
		q, err := quotedValue(entry.value)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", entry.key, err)
		}
		fmt.Fprintf(&b, "%s=%s\n", entry.key, q)
	}
	fmt.Fprintf(&b, "COLLECTION_PORT_BASE=%d\n", base)
	for _, r := range c.Registry.Repos {
		if r.PortOffset == nil {
			continue
		}
		key := portKey(r.Name)
		fmt.Fprintf(&b, "%s=%d\n", key, base+*r.PortOffset)
	}
	gh := filepath.Join(c.ConfigRoot, "gh")
	jira := filepath.Join(c.ConfigRoot, "jira")
	ghInfo, ghErr := os.Stat(gh)
	jiraInfo, jiraErr := os.Stat(jira)
	ghExists := ghErr == nil && ghInfo.IsDir()
	jiraExists := jiraErr == nil && jiraInfo.IsDir()
	twg, err := machineTWGSite(c.ConfigRoot)
	if err != nil {
		return nil, err
	}
	if ghExists || jiraExists || twg != "" {
		fmt.Fprintln(&b, "\n# Tool identity — workspace CLI stores, never credentials.")
		if ghExists {
			q, err := quotedValue(gh)
			if err != nil {
				return nil, err
			}
			fmt.Fprintf(&b, "GH_CONFIG_DIR=%s\n", q)
		}
		if jiraExists {
			q, err := quotedValue(filepath.Join(jira, ".config.yml"))
			if err != nil {
				return nil, err
			}
			fmt.Fprintf(&b, "JIRA_CONFIG_FILE=%s\n", q)
		}
		if twg != "" {
			q, err := quotedValue(twg)
			if err != nil {
				return nil, err
			}
			fmt.Fprintf(&b, "TWG_SITE=%s\n", q)
		}
	}
	return b.Bytes(), nil
}
func (c *Context) WriteEnv(data []byte) error {
	target := filepath.Join(c.Collection, ".env.collection")
	tmp, err := os.CreateTemp(c.Collection, ".env.collection.tmp-")
	if err != nil {
		return err
	}
	defer os.Remove(tmp.Name())
	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Chmod(0644); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	return os.Rename(tmp.Name(), target)
}

const miseHeader = `# Generated by wtc. Collection-scoped tools and env inherited by sibling worktrees.
`
const miseEnv = `[env]
_.file = [".env.collection", ".env.collection.local"]
`
const localEnvFile = `# Collection-scoped secrets and overrides. Hand-authored; never regenerated.
`

var cliVersionPattern = regexp.MustCompile(`^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$`)

func (c *Context) RenderMise() ([]byte, error) {
	var b bytes.Buffer
	b.WriteString(miseHeader)
	tools := make(map[string]string, len(c.Config.Mise.Tools)+1)
	for name, version := range c.Config.Mise.Tools {
		if strings.TrimSpace(name) == "" || strings.TrimSpace(version) == "" || strings.ContainsAny(name, "\r\n\x00") || strings.ContainsAny(version, "\r\n\x00") {
			return nil, fmt.Errorf("invalid mise tool %q or version %q", name, version)
		}
		tools[name] = version
	}
	versionFile := filepath.Join(c.Harness, ".wtc-cli-version")
	data, err := os.ReadFile(versionFile)
	if err != nil && !os.IsNotExist(err) {
		return nil, err
	}
	if err == nil {
		version := strings.TrimSpace(string(data))
		if !cliVersionPattern.MatchString(version) {
			return nil, fmt.Errorf("invalid CLI version in %s: %q", versionFile, version)
		}
		if _, exists := tools["github:lcorneliussen/wtc-cli"]; exists {
			return nil, fmt.Errorf("mise.tools must not override the committed CLI pin")
		}
		tools["github:lcorneliussen/wtc-cli"] = version
	}
	if len(tools) > 0 {
		b.WriteString("[tools]\n")
		names := make([]string, 0, len(tools))
		for name := range tools {
			names = append(names, name)
		}
		sort.Strings(names)
		for _, name := range names {
			fmt.Fprintf(&b, "%q = %q\n", name, tools[name])
		}
		b.WriteByte('\n')
	}
	b.WriteString(miseEnv)
	return b.Bytes(), nil
}

func (c *Context) EnsureEnvSupport() error {
	local := filepath.Join(c.Collection, ".env.collection.local")
	if err := c.ValidateEnvSupport(); err != nil {
		return err
	}
	mise, err := c.RenderMise()
	if err != nil {
		return err
	}
	if _, err := os.Lstat(local); os.IsNotExist(err) {
		f, err := os.OpenFile(local, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0600)
		if err != nil {
			return err
		}
		if _, err := f.WriteString(localEnvFile); err != nil {
			f.Close()
			return err
		}
		if err := f.Close(); err != nil {
			return err
		}
	} else if err != nil {
		return err
	}
	if err := os.Chmod(local, 0600); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(c.Collection, "mise.toml"), mise, 0644)
}

// TrustMise makes a freshly generated collection config usable by subsequent
// mise commands. A machine without mise can still generate the environment.
func (c *Context) TrustMise() error {
	mise, err := exec.LookPath("mise")
	if err != nil {
		if errors.Is(err, exec.ErrNotFound) {
			return nil
		}
		return err
	}
	config := filepath.Join(c.Collection, "mise.toml")
	cmd := exec.Command(mise, "trust", config)
	cmd.Dir = c.Collection
	if output, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("mise trust failed: %w: %s", err, strings.TrimSpace(string(output)))
	}
	return nil
}

func (c *Context) ValidateEnvSupport() error {
	local := filepath.Join(c.Collection, ".env.collection.local")
	info, err := os.Lstat(local)
	if err == nil && info.Mode()&os.ModeSymlink != 0 {
		return fmt.Errorf("refusing symlink: %s", local)
	}
	if err != nil && !os.IsNotExist(err) {
		return err
	}
	return nil
}
