package wtc

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

type MCPServer struct {
	Name      string `yaml:"name"`
	Transport string `yaml:"transport"`
	Command   string `yaml:"command"`
	Args      string `yaml:"args"`
	URL       string `yaml:"url"`
	Env       string `yaml:"env"`
	TokenEnv  string `yaml:"token_env"`
	Agents    string `yaml:"agents"`
	Enabled   *bool  `yaml:"enabled"`
}

type mcpRegistry struct {
	SchemaVersion int         `yaml:"schema_version"`
	Servers       []MCPServer `yaml:"servers"`
}

type MCPRender struct {
	Files   map[string][]byte `json:"-"`
	Missing []string          `json:"missing_env,omitempty"`
}

var envIdentifier = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]*$`)

func (c *Context) RenderMCP() (MCPRender, error) {
	path := filepath.Join(c.Harness, ".mcp-servers.yml")
	data, err := os.ReadFile(path)
	if err != nil {
		return MCPRender{}, err
	}
	var registry mcpRegistry
	if err := yaml.Unmarshal(data, &registry); err != nil {
		return MCPRender{}, fmt.Errorf("MCP registry: %w", err)
	}
	seen := map[string]bool{}
	missing := map[string]bool{}
	for _, s := range registry.Servers {
		if s.Name == "" || seen[s.Name] || strings.ContainsAny(s.Name, "\r\n\x00") {
			return MCPRender{}, fmt.Errorf("invalid or duplicate MCP server name %q", s.Name)
		}
		seen[s.Name] = true
		if s.Transport != "" && s.Transport != "stdio" && s.Transport != "http" {
			return MCPRender{}, fmt.Errorf("%s: unsupported transport %q", s.Name, s.Transport)
		}
		if s.Transport == "http" && s.URL == "" || s.Transport != "http" && s.Command == "" {
			return MCPRender{}, fmt.Errorf("%s: missing URL or command", s.Name)
		}
		for _, v := range append(strings.Fields(s.Env), strings.Fields(s.TokenEnv)...) {
			if !envIdentifier.MatchString(v) {
				return MCPRender{}, fmt.Errorf("%s: invalid env variable %q", s.Name, v)
			}
			if s.Enabled == nil || *s.Enabled {
				if os.Getenv(v) == "" {
					missing[v] = true
				}
			}
		}
		for _, agent := range strings.Fields(s.Agents) {
			if agent != "claude" && agent != "cursor" && agent != "codex" {
				return MCPRender{}, fmt.Errorf("%s: unknown agent %q", s.Name, agent)
			}
		}
	}
	files := map[string][]byte{}
	for _, agent := range []string{"claude", "cursor"} {
		servers := map[string]any{}
		for _, s := range registry.Servers {
			if !mcpEnabledFor(s, agent) {
				continue
			}
			servers[s.Name] = mcpJSONServer(s)
		}
		body, err := json.MarshalIndent(map[string]any{"_generated": "wtc mcp render — edits are overwritten; change harness/.mcp-servers.yml", "mcpServers": servers}, "", "  ")
		if err != nil {
			return MCPRender{}, err
		}
		body = append(body, '\n')
		if agent == "claude" {
			files[".mcp.json"] = body
		} else {
			files[".cursor/mcp.json"] = body
		}
	}
	var toml bytes.Buffer
	toml.WriteString("# Generated by wtc mcp render — edits are overwritten.\n# Change harness/.mcp-servers.yml and re-run.\n")
	for _, s := range registry.Servers {
		if !mcpEnabledFor(s, "codex") {
			continue
		}
		fmt.Fprintf(&toml, "\n[mcp_servers.%q]\n", s.Name)
		if s.Transport == "http" {
			fmt.Fprintf(&toml, "url = %q\n", s.URL)
			if s.TokenEnv != "" {
				fmt.Fprintf(&toml, "bearer_token_env_var = %q\n", s.TokenEnv)
			}
		} else {
			fmt.Fprintf(&toml, "command = %q\n", s.Command)
			if s.Args != "" {
				fmt.Fprintf(&toml, "args = %s\n", jsonArray(strings.Fields(s.Args)))
			}
			if s.Env != "" {
				fmt.Fprintf(&toml, "env_vars = %s\n", jsonArray(strings.Fields(s.Env)))
			}
		}
	}
	files[".codex/config.toml"] = toml.Bytes()
	var missingNames []string
	for name := range missing {
		missingNames = append(missingNames, name)
	}
	sort.Strings(missingNames)
	return MCPRender{Files: files, Missing: missingNames}, nil
}

func mcpEnabledFor(s MCPServer, agent string) bool {
	if s.Enabled != nil && !*s.Enabled {
		return false
	}
	if s.Agents == "" {
		return true
	}
	for _, name := range strings.Fields(s.Agents) {
		if name == agent {
			return true
		}
	}
	return false
}

func mcpJSONServer(s MCPServer) map[string]any {
	item := map[string]any{}
	if s.Transport == "http" {
		item["type"] = "http"
		item["url"] = s.URL
		if s.TokenEnv != "" {
			item["headers"] = map[string]string{"Authorization": "Bearer ${" + s.TokenEnv + "}"}
		}
	} else {
		item["command"] = s.Command
		if s.Args != "" {
			item["args"] = strings.Fields(s.Args)
		}
		if s.Env != "" {
			env := map[string]string{}
			for _, name := range strings.Fields(s.Env) {
				env[name] = "${" + name + "}"
			}
			item["env"] = env
		}
	}
	return item
}

func jsonArray(items []string) string {
	data, _ := json.Marshal(items)
	return string(data)
}

// WriteMCP reports changed generated paths. A dry run leaves all files alone.
func (c *Context) WriteMCP(render MCPRender, dryRun bool) ([]string, error) {
	paths := []string{".mcp.json", ".cursor/mcp.json", ".codex/config.toml"}
	var changed []string
	for _, rel := range paths {
		target := filepath.Join(c.Collection, rel)
		info, err := os.Lstat(target)
		if err == nil && !info.Mode().IsRegular() {
			return nil, fmt.Errorf("refusing non-regular generated MCP file: %s", target)
		}
		if err != nil && !os.IsNotExist(err) {
			return nil, err
		}
		old, err := os.ReadFile(target)
		if err != nil && !os.IsNotExist(err) {
			return nil, err
		}
		if !bytes.Equal(old, render.Files[rel]) {
			changed = append(changed, rel)
		}
	}
	if dryRun {
		return changed, nil
	}
	for _, rel := range changed {
		target := filepath.Join(c.Collection, rel)
		if err := os.MkdirAll(filepath.Dir(target), 0755); err != nil {
			return changed, err
		}
		if err := os.WriteFile(target, render.Files[rel], 0644); err != nil {
			return changed, err
		}
	}
	return changed, nil
}
