package wtc

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type RegistryRefresh struct {
	Path       string   `json:"path"`
	BareOwners []string `json:"bare_owners"`
	Missing    []string `json:"missing"`
	Unlisted   []string `json:"unlisted"`
}

// RefreshRegistry writes the local bare-owner map used by legacy commands.
// The tracked registry remains the source of remote and branch metadata.
func (c *Context) RefreshRegistry() (RegistryRefresh, error) {
	bareDir := filepath.Join(c.Workspace, ".bare")
	entries, err := os.ReadDir(bareDir)
	if err != nil {
		return RegistryRefresh{}, fmt.Errorf("read bare owners: %w", err)
	}
	report := RegistryRefresh{Path: filepath.Join(c.Harness, ".harness-repos")}
	paths := map[string]string{}
	for _, e := range entries {
		if !strings.HasSuffix(e.Name(), ".git") {
			continue
		}
		path := filepath.Join(bareDir, e.Name())
		info, err := os.Stat(path)
		if err != nil || !info.IsDir() {
			continue
		}
		name := strings.TrimSuffix(e.Name(), ".git")
		paths[name] = path
		report.BareOwners = append(report.BareOwners, name)
	}
	sort.Strings(report.BareOwners)
	registered := map[string]bool{}
	for _, repo := range c.Registry.Repos {
		registered[repo.Name] = true
		if _, ok := paths[repo.Name]; !ok {
			report.Missing = append(report.Missing, repo.Name)
		}
	}
	for _, name := range report.BareOwners {
		if !registered[name] {
			report.Unlisted = append(report.Unlisted, name)
		}
	}
	var b bytes.Buffer
	b.WriteString("# Generated by wtc registry refresh — local bare-owner paths.\n# Tracked counterpart: .harness-repos.yml\n")
	for _, name := range report.BareOwners {
		fmt.Fprintf(&b, "%s=%s\n", name, paths[name])
	}
	if info, err := os.Lstat(report.Path); err == nil && !info.Mode().IsRegular() {
		return report, fmt.Errorf("refusing non-regular registry map: %s", report.Path)
	} else if err != nil && !os.IsNotExist(err) {
		return report, err
	}
	tmp, err := os.CreateTemp(c.Harness, ".harness-repos.tmp-")
	if err != nil {
		return report, err
	}
	defer os.Remove(tmp.Name())
	if _, err := tmp.Write(b.Bytes()); err != nil {
		tmp.Close()
		return report, err
	}
	if err := tmp.Chmod(0644); err != nil {
		tmp.Close()
		return report, err
	}
	if err := tmp.Close(); err != nil {
		return report, err
	}
	return report, os.Rename(tmp.Name(), report.Path)
}
