package wtc

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"gopkg.in/yaml.v3"
)

type statusLegacyCache struct {
	GeneratedAt string                  `yaml:"generated_at"`
	GeneratedBy string                  `yaml:"generated_by"`
	Collection  string                  `yaml:"collection"`
	Repos       []statusLegacyCacheRepo `yaml:"repos"`
}

type statusLegacyCacheRepo struct {
	Repo   string `yaml:"repo"`
	Branch string `yaml:"branch"`
	Head   string `yaml:"head"`
	Ahead  int    `yaml:"ahead"`
	Behind int    `yaml:"behind"`
	Tree   string `yaml:"tree"`
	PR     string `yaml:"pr"`
	Forge  string `yaml:"forge"`
	State  string `yaml:"state"`
	Checks string `yaml:"checks"`
	Merge  string `yaml:"merge"`
	Review string `yaml:"review"`
	Title  string `yaml:"title"`
}

func statusAtomicWrite(path string, data []byte) error {
	tmp, err := os.CreateTemp(filepath.Dir(path), ".wtc-status-")
	if err != nil {
		return err
	}
	defer os.Remove(tmp.Name())
	if err := tmp.Chmod(0644); err != nil {
		tmp.Close()
		return err
	}
	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	return os.Rename(tmp.Name(), path)
}

func (c *Context) statusLegacy(snapshot StatusSnapshot) statusLegacyCache {
	legacy := statusLegacyCache{GeneratedAt: snapshot.GeneratedAt, GeneratedBy: "wtc status",
		Collection: snapshot.Collection, Repos: []statusLegacyCacheRepo{}}
	for _, row := range snapshot.Repos {
		item := statusLegacyCacheRepo{Repo: row.Dir, Branch: row.BranchDisplay, Ahead: row.Ahead,
			Behind: row.Behind, Tree: row.Tree, Forge: "unknown"}
		item.Head, _ = statusGit(row.Worktree, "rev-parse", "--short", "HEAD")
		_, forge := c.statusRecordForge(PRRecord{Repo: row.Repo}, snapshot.Repos)
		item.Forge = strings.TrimSuffix(forge, ".com")
		if forge == "bitbucket.org" {
			item.Forge = "bitbucket"
		}
		if item.Forge == "" {
			item.Forge = "unknown"
		}
		if row.PR != nil {
			item.PR = row.PR.Number
			item.Checks = row.PR.Checks
			item.Merge = row.PR.Merge
			item.Review = row.PR.Review
			item.State = "OPEN"
			if row.PR.Draft {
				item.State = "DRAFT"
			}
		}
		legacy.Repos = append(legacy.Repos, item)
	}
	return legacy
}

func statusLegacyQuote(value string) string {
	value = strings.Join(strings.Fields(value), " ")
	return "'" + strings.ReplaceAll(value, "'", "''") + "'"
}

// The shell reader strips single quotes and doubled apostrophes, so preserve
// its narrow YAML subset rather than relying on a marshaler's quoting style.
func statusLegacyYAML(cache statusLegacyCache) []byte {
	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by wtc status — the last completed refresh.\n")
	fmt.Fprintf(&b, "generated_at: %s\n", statusLegacyQuote(cache.GeneratedAt))
	fmt.Fprintf(&b, "generated_by: %s\n", statusLegacyQuote(cache.GeneratedBy))
	fmt.Fprintf(&b, "collection: %s\nrepos:\n", statusLegacyQuote(cache.Collection))
	for _, repo := range cache.Repos {
		fmt.Fprintf(&b, "  - repo: %s\n", statusLegacyQuote(repo.Repo))
		fmt.Fprintf(&b, "    branch: %s\n", statusLegacyQuote(repo.Branch))
		fmt.Fprintf(&b, "    head: %s\n", statusLegacyQuote(repo.Head))
		fmt.Fprintf(&b, "    ahead: %d\n", repo.Ahead)
		fmt.Fprintf(&b, "    behind: %d\n", repo.Behind)
		fmt.Fprintf(&b, "    tree: %s\n", statusLegacyQuote(repo.Tree))
		fmt.Fprintf(&b, "    pr: %s\n", statusLegacyQuote(repo.PR))
		fmt.Fprintf(&b, "    forge: %s\n", statusLegacyQuote(repo.Forge))
		fmt.Fprintf(&b, "    state: %s\n", statusLegacyQuote(repo.State))
		fmt.Fprintf(&b, "    checks: %s\n", statusLegacyQuote(repo.Checks))
		fmt.Fprintf(&b, "    merge: %s\n", statusLegacyQuote(repo.Merge))
		fmt.Fprintf(&b, "    review: %s\n", statusLegacyQuote(repo.Review))
		fmt.Fprintf(&b, "    title: %s\n", statusLegacyQuote(repo.Title))
	}
	return []byte(b.String())
}

// WriteStatusSnapshot publishes a completed scoped snapshot in the three
// formats consumed by current status readers. Preview commands never call it.
func (c *Context) WriteStatusSnapshot(snapshot StatusSnapshot) error {
	if snapshot.Schema != 1 || snapshot.Collection != filepath.Base(c.Collection) || snapshot.ShowCollectionColumn {
		return fmt.Errorf("snapshot does not describe this collection")
	}
	canonical, err := json.MarshalIndent(snapshot, "", "  ")
	if err != nil {
		return err
	}
	canonical = append(canonical, '\n')
	legacy := statusLegacyYAML(c.statusLegacy(snapshot))
	files := []struct {
		name string
		data []byte
	}{{".wtc-status.json", canonical}, {".wtc-status.md", []byte(snapshot.Markdown())}, {".last-wtc-status.yml", legacy}}
	for _, file := range files {
		if err := statusAtomicWrite(filepath.Join(c.Collection, file.name), file.data); err != nil {
			return fmt.Errorf("write %s: %w", file.name, err)
		}
	}
	return nil
}

func (c *Context) ReadStatusSnapshot() (StatusSnapshot, error) {
	path := filepath.Join(c.Collection, ".wtc-status.json")
	data, err := os.ReadFile(path)
	if err != nil {
		return StatusSnapshot{}, err
	}
	var snapshot StatusSnapshot
	if err := json.Unmarshal(data, &snapshot); err != nil {
		return StatusSnapshot{}, fmt.Errorf("decode cached status: %w", err)
	}
	if snapshot.Schema != 1 || snapshot.Collection != filepath.Base(c.Collection) {
		return StatusSnapshot{}, fmt.Errorf("cached status has wrong schema or collection")
	}
	return snapshot, nil
}

func (c *Context) CachedStatusAge() (int, error) {
	for _, name := range []string{".wtc-status.json", ".last-wtc-status.yml"} {
		info, err := os.Stat(filepath.Join(c.Collection, name))
		if err == nil {
			age := int(time.Since(info.ModTime()).Seconds())
			if age < 0 {
				age = 0
			}
			return age, nil
		}
		if !os.IsNotExist(err) {
			return 0, err
		}
	}
	return 0, os.ErrNotExist
}

// LegacyStatusText is the plain fallback when the canonical cache is absent.
// It only claims the columns present in the old YAML file.
func (c *Context) LegacyStatusText() (string, error) {
	data, err := os.ReadFile(filepath.Join(c.Collection, ".last-wtc-status.yml"))
	if err != nil {
		return "", err
	}
	var legacy statusLegacyCache
	if err := yaml.Unmarshal(data, &legacy); err != nil {
		return "", err
	}
	if legacy.Collection != filepath.Base(c.Collection) {
		return "", fmt.Errorf("legacy status cache is for another collection")
	}
	age, err := c.CachedStatusAge()
	if err != nil {
		return "", err
	}
	var b strings.Builder
	fmt.Fprintf(&b, "%s — cached %ds old (.last-wtc-status.yml; no .wtc-status.json)\n", legacy.Collection, age)
	fmt.Fprintf(&b, "%-16s %-24s %-8s %-4s %-4s %s\n", "REPO", "BRANCH", "PR", "AHEAD", "BEHIND", "TREE")
	for _, row := range legacy.Repos {
		pr := ""
		if row.PR != "" {
			pr = "#" + row.PR
		}
		fmt.Fprintf(&b, "%-16s %-24s %-8s %-4d %-4d %s\n", row.Repo, row.Branch, pr, row.Ahead, row.Behind, row.Tree)
	}
	return b.String(), nil
}
